import { Property } from '../types/property';
import { Conversation } from '../types/chat';
import { Booking } from '../types/booking';
import { User } from '../types/user';

export const DUMMY_USER: User = {
  id: 'user-1',
  name: 'Rahul Sharma',
  email: 'rahul.sharma@email.com',
  phone: '+91 98765 43210',
  avatarUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
  isVerified: true,
  createdAt: '2024-01-15T10:00:00Z',
  totalProperties: 2,
  totalBookings: 5,
};

export const DUMMY_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'Spacious 2BHK in Koramangala',
    description: 'A beautiful fully furnished 2BHK apartment in the heart of Koramangala with modern amenities, close to all major tech parks and restaurants.',
    type: 'apartment',
    bhk: '2BHK',
    furnishedStatus: 'furnished',
    listingType: 'rent',
    status: 'available',
    rent: 35000,
    deposit: 70000,
    area: 1100,
    floor: 3,
    totalFloors: 6,
    bathrooms: 2,
    parking: true,
    petFriendly: false,
    location: {
      address: '12th Main Rd, Koramangala',
      locality: 'Koramangala',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560034',
      latitude: 12.9279,
      longitude: 77.6271,
    },
    amenities: [
      { id: 'a1', name: 'WiFi', icon: 'wifi' },
      { id: 'a2', name: 'AC', icon: 'wind' },
      { id: 'a3', name: 'Gym', icon: 'dumbbell' },
      { id: 'a4', name: 'Swimming Pool', icon: 'waves' },
    ],
    images: [
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2724748/pexels-photo-2724748.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    ownerId: 'owner-1',
    ownerName: 'Priya Nair',
    ownerAvatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    isOwnerVerified: true,
    isAvailableFrom: '2025-02-01',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
    isFavorite: true,
    viewCount: 234,
  },
  {
    id: 'prop-2',
    title: 'Modern 3BHK Villa in Whitefield',
    description: 'Luxurious 3BHK villa with private garden and premium finishes. Ideal for families looking for spacious living near IT corridor.',
    type: 'villa',
    bhk: '3BHK',
    furnishedStatus: 'semi-furnished',
    listingType: 'rent',
    status: 'available',
    rent: 65000,
    deposit: 195000,
    area: 2200,
    floor: 0,
    totalFloors: 2,
    bathrooms: 3,
    parking: true,
    petFriendly: true,
    location: {
      address: 'ITPL Main Road, Whitefield',
      locality: 'Whitefield',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560066',
      latitude: 12.9698,
      longitude: 77.7499,
    },
    amenities: [
      { id: 'a1', name: 'WiFi', icon: 'wifi' },
      { id: 'a5', name: 'Garden', icon: 'tree-pine' },
      { id: 'a6', name: 'Security', icon: 'shield' },
    ],
    images: [
      'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    ownerId: 'owner-2',
    ownerName: 'Arun Kumar',
    ownerAvatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    isOwnerVerified: true,
    isAvailableFrom: '2025-02-15',
    createdAt: '2025-01-05T10:00:00Z',
    updatedAt: '2025-01-05T10:00:00Z',
    isFavorite: false,
    viewCount: 187,
  },
  {
    id: 'prop-3',
    title: 'Cozy 1BHK near MG Road',
    description: 'Affordable and well-maintained 1BHK apartment just 5 minutes from MG Road metro station. Perfect for young professionals.',
    type: 'apartment',
    bhk: '1BHK',
    furnishedStatus: 'furnished',
    listingType: 'rent',
    status: 'available',
    rent: 18000,
    deposit: 36000,
    area: 550,
    floor: 2,
    totalFloors: 5,
    bathrooms: 1,
    parking: false,
    petFriendly: false,
    location: {
      address: 'Residency Road, Richmond Town',
      locality: 'Richmond Town',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560025',
      latitude: 12.9716,
      longitude: 77.6197,
    },
    amenities: [
      { id: 'a1', name: 'WiFi', icon: 'wifi' },
      { id: 'a2', name: 'AC', icon: 'wind' },
    ],
    images: [
      'https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    ownerId: 'owner-3',
    ownerName: 'Deepika Menon',
    ownerAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
    isOwnerVerified: false,
    isAvailableFrom: '2025-01-20',
    createdAt: '2025-01-12T14:00:00Z',
    updatedAt: '2025-01-12T14:00:00Z',
    isFavorite: true,
    viewCount: 89,
  },
  {
    id: 'prop-4',
    title: 'Premium 4BHK Penthouse in Indiranagar',
    description: 'Stunning penthouse apartment with rooftop terrace, panoramic city views, and ultra-premium finishes in one of Bangalore\'s most sought-after neighbourhoods.',
    type: 'apartment',
    bhk: '4BHK',
    furnishedStatus: 'furnished',
    listingType: 'rent',
    status: 'available',
    rent: 120000,
    deposit: 360000,
    area: 3500,
    floor: 12,
    totalFloors: 12,
    bathrooms: 4,
    parking: true,
    petFriendly: true,
    location: {
      address: '100 Feet Road, Indiranagar',
      locality: 'Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560038',
      latitude: 12.9784,
      longitude: 77.6408,
    },
    amenities: [
      { id: 'a1', name: 'WiFi', icon: 'wifi' },
      { id: 'a2', name: 'AC', icon: 'wind' },
      { id: 'a3', name: 'Gym', icon: 'dumbbell' },
      { id: 'a4', name: 'Pool', icon: 'waves' },
      { id: 'a7', name: 'Terrace', icon: 'home' },
    ],
    images: [
      'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    ownerId: 'owner-4',
    ownerName: 'Vikram Singh',
    ownerAvatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=200',
    isOwnerVerified: true,
    isAvailableFrom: '2025-03-01',
    createdAt: '2025-01-08T09:00:00Z',
    updatedAt: '2025-01-08T09:00:00Z',
    isFavorite: false,
    viewCount: 512,
  },
  {
    id: 'prop-5',
    title: 'Affordable 2BHK in HSR Layout',
    description: 'Well-connected 2BHK with good ventilation and natural light. Close to HSR Layout BDA Complex and all daily amenities.',
    type: 'apartment',
    bhk: '2BHK',
    furnishedStatus: 'unfurnished',
    listingType: 'rent',
    status: 'available',
    rent: 22000,
    deposit: 44000,
    area: 900,
    floor: 1,
    totalFloors: 3,
    bathrooms: 2,
    parking: true,
    petFriendly: false,
    location: {
      address: '27th Main, HSR Layout',
      locality: 'HSR Layout',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560102',
      latitude: 12.9116,
      longitude: 77.6473,
    },
    amenities: [
      { id: 'a6', name: 'Security', icon: 'shield' },
    ],
    images: [
      'https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    ownerId: 'owner-5',
    ownerName: 'Suresh Reddy',
    isOwnerVerified: false,
    isAvailableFrom: '2025-02-01',
    createdAt: '2025-01-14T11:00:00Z',
    updatedAt: '2025-01-14T11:00:00Z',
    isFavorite: false,
    viewCount: 67,
  },
];

export const DUMMY_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    participantId: 'owner-1',
    participantName: 'Priya Nair',
    participantAvatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    lastMessage: 'The flat is available for viewing this weekend.',
    lastMessageTime: '2025-01-15T10:30:00Z',
    unreadCount: 2,
    propertyId: 'prop-1',
    propertyTitle: 'Spacious 2BHK in Koramangala',
    propertyImage: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'conv-2',
    participantId: 'owner-2',
    participantName: 'Arun Kumar',
    participantAvatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    lastMessage: 'Hi, I saw your query about the villa.',
    lastMessageTime: '2025-01-14T17:45:00Z',
    unreadCount: 0,
    propertyId: 'prop-2',
    propertyTitle: 'Modern 3BHK Villa in Whitefield',
    propertyImage: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'conv-3',
    participantId: 'owner-4',
    participantName: 'Vikram Singh',
    participantAvatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=200',
    lastMessage: 'Deposit is negotiable for long-term tenants.',
    lastMessageTime: '2025-01-13T09:15:00Z',
    unreadCount: 1,
    propertyId: 'prop-4',
    propertyTitle: 'Premium 4BHK Penthouse in Indiranagar',
    propertyImage: 'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
];

export const DUMMY_BOOKINGS: Booking[] = [
  {
    id: 'booking-1',
    propertyId: 'prop-1',
    propertyTitle: 'Spacious 2BHK in Koramangala',
    propertyImage: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400',
    tenantId: 'user-1',
    ownerId: 'owner-1',
    ownerName: 'Priya Nair',
    status: 'confirmed',
    visitDate: '2025-01-20',
    visitTime: '11:00 AM',
    message: 'Please allow me to visit with my family.',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T14:00:00Z',
  },
  {
    id: 'booking-2',
    propertyId: 'prop-3',
    propertyTitle: 'Cozy 1BHK near MG Road',
    propertyImage: 'https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=400',
    tenantId: 'user-1',
    ownerId: 'owner-3',
    ownerName: 'Deepika Menon',
    status: 'pending',
    visitDate: '2025-01-22',
    visitTime: '3:00 PM',
    createdAt: '2025-01-14T09:00:00Z',
    updatedAt: '2025-01-14T09:00:00Z',
  },
];

export const PROPERTY_CATEGORIES = [
  { id: 'all', label: 'All', icon: 'grid' },
  { id: 'apartment', label: 'Apartment', icon: 'building-2' },
  { id: 'villa', label: 'Villa', icon: 'home' },
  { id: 'house', label: 'House', icon: 'house' },
  { id: 'pg', label: 'PG', icon: 'users' },
  { id: 'studio', label: 'Studio', icon: 'square' },
  { id: 'commercial', label: 'Commercial', icon: 'briefcase' },
];

export const POPULAR_CITIES = [
  'Bengaluru', 'Mumbai', 'Delhi', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad',
];
